name: Check mssql

on:
  push:
    branches: [ dev ]
  pull_request:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run the action
      uses: potatoqualitee/mssqlsuite@v1
      with:
        install: sqlengine, sqlpackage

    - name: Run sqlclient
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
      
    - name: Create Database
      run: |
        sqlcmd -S localhost -U sa -P dbatools.I0 -b -i scripts/database.sql || exit 1
        
    - name: Create Tables
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -b -i scripts/table.sql || exit 1
    
    - name: Create Triggers
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -b -i scripts/triggers.sql || exit 1
      
    - name: Insert Data
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -b -i scripts/data.sql || exit 1
      
    - name: Run Tests
      run: sqlcmd -S localhost -U sa -P dbatools.I0 -d FUDormitory -b -i scripts/test.sql || exit 1
